import Link from 'next/link'
import Image from 'next/image'
import { ArrowUpRight, Github, Linkedin } from 'lucide-react'

const skills = ['React', 'Next.js', 'TypeScript', 'Node.js', 'Firebase', 'PostgreSQL', 'Python', 'Tailwind CSS', 'Vercel', 'Git']

export default function AboutPage() {
  return <div className="page-shell">
    <section className="grid gap-12 py-20 md:grid-cols-[1fr_0.72fr] md:items-end md:py-28"><div><p className="eyebrow mb-5">About · Jhye O&apos;Meley</p><h1 className="max-w-3xl font-['Space_Grotesk'] text-5xl font-bold leading-[1.02] tracking-[-0.04em] md:text-7xl">A developer who likes making complicated things feel simple.</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-[var(--muted)]">I&apos;m a 23-year-old full-stack developer from Australia, currently based in Tokyo. I build web products, automation, and operational systems that help people do better work.</p><div className="mt-8 flex gap-5 text-sm font-bold"><a className="focus-ring inline-flex items-center gap-2 hover:text-[var(--accent)]" href="https://github.com/TheJhyeFactor" target="_blank" rel="noreferrer"><Github className="h-4 w-4" />GitHub</a><a className="focus-ring inline-flex items-center gap-2 hover:text-[var(--accent)]" href="https://www.linkedin.com/in/jhye-o-meley-529960213/" target="_blank" rel="noreferrer"><Linkedin className="h-4 w-4" />LinkedIn</a></div></div><div className="relative aspect-[4/5] overflow-hidden bg-[#e8e3da]"><Image src="/images/projects/Headshot.jpeg" alt="Jhye O'Meley" fill className="object-cover" /></div></section>
    <section className="section-rule grid gap-12 py-16 md:grid-cols-[0.7fr_1.3fr]"><div><p className="eyebrow mb-3">The short version</p><h2 className="font-['Space_Grotesk'] text-3xl font-bold tracking-tight">Built by shipping.</h2></div><div className="space-y-5 text-lg leading-8 text-[var(--muted)]"><p>Over the last four years I&apos;ve delivered 22 projects across logistics, education, creator tools, trade software, transport operations, and internal business systems.</p><p>I care about the point where product thinking meets implementation: understanding the real workflow, making the important path obvious, and leaving behind software that is easier to maintain than it was to start.</p><p>My current work spans five product platforms — Buildly, TradieFlow, TripMate, Castivo, and QuickMeet — alongside client systems and smaller experiments.</p></div></section>
    <section className="section-rule grid gap-12 py-16 md:grid-cols-[0.7fr_1.3fr]"><div><p className="eyebrow mb-3">Toolkit</p><h2 className="font-['Space_Grotesk'] text-3xl font-bold tracking-tight">The tools I use.</h2></div><div className="flex flex-wrap gap-x-6 gap-y-4 text-lg text-[var(--muted)]">{skills.map((skill) => <span key={skill}>{skill}</span>)}</div></section>
    <section className="section-rule flex flex-col justify-between gap-6 py-16 md:flex-row md:items-end"><div><p className="eyebrow mb-3">Next step</p><h2 className="max-w-xl font-['Space_Grotesk'] text-3xl font-bold tracking-tight md:text-4xl">Want to see how I work?</h2></div><Link href="/portfolio/" className="focus-ring inline-flex items-center gap-2 text-sm font-bold text-[var(--accent)] hover:underline">View selected work <ArrowUpRight className="h-4 w-4" /></Link></section>
  </div>
}
