import Link from 'next/link'
import { ArrowUpRight } from 'lucide-react'
import ProjectCard from '@/components/ProjectCard'

const products = [
  { title: 'Buildly', description: 'A creator-learning platform where students explore, build, test, and share technology through guided classroom missions.', image: '/images/projects/screenshots/buildly.png', tags: ['React', 'Education', 'Product Design', 'Vercel'], year: 2026, href: 'https://buildly-showcase.vercel.app/' },
  { title: 'TradieFlow', description: 'Live profit tracking for trade businesses, helping owners understand labour, materials, targets, and job performance while work is still underway.', image: '/images/projects/screenshots/tradieflow.png', tags: ['Next.js', 'SaaS', 'Fintech', 'Job Management'], year: 2026, href: 'https://tradieflow-pi.vercel.app/' },
  { title: 'TripMate', description: 'Operations software for transport teams, connecting bookings, riders, drivers, live route monitoring, and trip coordination in one workspace.', image: '/images/projects/screenshots/tripmate.png', tags: ['React', 'Firebase', 'Operations', 'Mobile Companion'], year: 2026, href: 'https://tripmate-platform.vercel.app/' },
  { title: 'Castivo', description: 'A platform for streamers to create and manage branded websites, with audience engagement tools such as leaderboards, raffles, and bonus-hunt tracking.', image: '/images/projects/screenshots/castivo.png', tags: ['Next.js', 'Firebase', 'Creator Tools', 'SaaS'], year: 2026, href: 'https://castivo-web-thejhyefactors-projects.vercel.app/' },
  { title: 'QuickMeet', description: 'A focused meeting platform for starting secure conversations quickly, with a polished landing surface and an iOS companion on the way.', image: '/images/projects/screenshots/quickmeet.png', tags: ['React', 'WebRTC', 'Firebase', 'Real-time'], year: 2026, href: 'https://www.quickmeet.cam/' },
]
const clientWork = [
  { title: 'TransportationME', description: 'Logistics platform for route planning, fleet tracking, and real-time operations.', image: '/images/projects/transportation-me.png', tags: ['WordPress', 'Dashboard', 'Automation'], year: 2025, href: 'https://transportationme.au/' },
  { title: 'PC Choices', description: 'E-commerce experience with product pages, a PC configurator, cart, and checkout.', image: '/images/projects/pc-choice.png', tags: ['E-Commerce', 'React', 'Web Development'], year: 2023, href: 'https://pc-choice.com.au/' },
  { title: 'AEO Services Portal', description: 'Internal project tracking, communication, and resource management for a services team.', image: '/images/projects/aeo-portal.svg', tags: ['Dashboard', 'Project Management'], year: 2024 },
  { title: 'NDIS Admin System', description: 'Administration and compliance tooling for participant and service management.', image: '/images/projects/ndis-admin.svg', tags: ['Admin System', 'Automation'], year: 2024 },
  { title: 'TJ Pizza Hut', description: 'Online ordering flow with menu browsing, customisation, payment, and delivery tracking.', image: '/images/projects/tj-pizza.svg', tags: ['Web App', 'Ordering System'], year: 2021 },
  { title: 'ECBC Promotion Video', description: 'End-to-end promotional video production, from scripting and direction to editing.', image: '/images/projects/ecbc-video.svg', tags: ['Video', 'Editing', 'Directing'], year: 2025 },
]
const experiments = [
  ['CareerLift', 'Resume builder with ATS-friendly templates and private client-side processing.', '/images/projects/CareeLift.jpeg', 'https://thejhyefactor.github.io/careerlift/'],
  ['Real-Time Object Detection', 'Browser computer-vision experiment using TensorFlow.js.', '/images/projects/Realtimeobj.jpeg', 'https://thejhyefactor.github.io/object-detection/'],
  ['Browser OS', 'A browser desktop with draggable windows, terminal, and local persistence.', '/images/projects/webos.jpeg', 'https://thejhyefactor.github.io/browser-os/'],
  ['VideoFlow', 'Browser-based video editor with overlays, effects, and export controls.', '/images/projects/videoflow.jpeg', 'https://thejhyefactor.github.io/video-editor/'],
  ['InvoicePro', 'Private invoice generation and PDF export for freelancers and small businesses.', '/images/projects/invoice.png', 'https://thejhyefactor.github.io/invoice-generator/'],
  ['PDF Tools', 'Client-side tools for merging, splitting, compressing, and converting PDFs.', '/images/projects/pdf.png', 'https://thejhyefactor.github.io/pdf-tools/'],
]

export default function PortfolioPage() {
  return <div className="page-shell">
    <section className="py-20 md:py-28"><p className="eyebrow mb-5">Portfolio · 22 projects</p><h1 className="max-w-3xl font-['Space_Grotesk'] text-5xl font-bold leading-[1.02] tracking-[-0.04em] md:text-7xl">A selection of products, systems, and experiments.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[var(--muted)]">I work across product design, full-stack development, automation, and operational software. These are the builds that best show how I think and work.</p></section>
    <section className="section-rule py-16"><div className="mb-10 flex items-end justify-between gap-6"><div><p className="eyebrow mb-3">01 · Selected work</p><h2 className="font-['Space_Grotesk'] text-3xl font-bold tracking-tight md:text-4xl">Products built</h2></div><span className="text-sm text-[var(--muted)]">5 platforms</span></div><div className="grid gap-6 md:grid-cols-2">{products.map((project) => <ProjectCard key={project.title} {...project} featured />)}</div></section>
    <section className="section-rule py-16"><div className="mb-10 flex items-end justify-between gap-6"><div><p className="eyebrow mb-3">02 · Client work</p><h2 className="font-['Space_Grotesk'] text-3xl font-bold tracking-tight md:text-4xl">Systems that ship.</h2></div><span className="text-sm text-[var(--muted)]">6 projects</span></div><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{clientWork.map((project) => <ProjectCard key={project.title} {...project} />)}</div></section>
    <section className="section-rule py-16"><div className="mb-10 flex items-end justify-between gap-6"><div><p className="eyebrow mb-3">03 · Experiments</p><h2 className="font-['Space_Grotesk'] text-3xl font-bold tracking-tight md:text-4xl">Things I built to learn.</h2></div><span className="text-sm text-[var(--muted)]">6 of 11 experiments</span></div><div className="divide-y divide-[var(--border)] border-y border-[var(--border)]">{experiments.map(([title, description, , href]) => <a key={title} href={href} target="_blank" rel="noreferrer" className="focus-ring flex items-center justify-between gap-5 py-5 hover:text-[var(--accent)]"><span><strong className="block font-['Space_Grotesk'] text-lg text-[var(--ink)]">{title}</strong><span className="text-sm text-[var(--muted)]">{description}</span></span><ArrowUpRight className="h-5 w-5 shrink-0 text-[var(--accent)]" /></a>)}</div><p className="mt-5 text-sm text-[var(--muted)]">More tools, including Social Dashboard, Stock Price Visualizer, Pomodoro Timer, Particle Physics Playground, and Background Remover, remain available in the wider project archive.</p></section>
    <section className="section-rule py-16"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="eyebrow mb-3">Let&apos;s talk</p><h2 className="max-w-xl font-['Space_Grotesk'] text-3xl font-bold tracking-tight md:text-4xl">Looking for someone who can take an idea through to a working product?</h2></div><Link href="/contact/" className="focus-ring inline-flex items-center gap-2 text-sm font-bold text-[var(--accent)] hover:underline">Contact me <ArrowUpRight className="h-4 w-4" /></Link></div></section>
  </div>
}
