import Link from 'next/link'
import { ArrowUpRight, Github, Linkedin, Mail } from 'lucide-react'
import ProjectCard from '@/components/ProjectCard'

const products = [
  { title: 'Buildly', description: 'A creator-learning platform for guided classroom missions and build-first lessons.', image: '/images/projects/screenshots/buildly.png', tags: ['React', 'Education', 'Product Design'], href: 'https://buildly-showcase.vercel.app/', year: 2026 },
  { title: 'TradieFlow', description: 'Live profit tracking for trade businesses, from job costs to targets and performance.', image: '/images/projects/screenshots/tradieflow.png', tags: ['Next.js', 'SaaS', 'Job Management'], href: 'https://tradieflow-pi.vercel.app/', year: 2026 },
  { title: 'TripMate', description: 'Operations software connecting bookings, riders, drivers, routes, and trip coordination.', image: '/images/projects/screenshots/tripmate.png', tags: ['React', 'Firebase', 'Operations'], href: 'https://tripmate-platform.vercel.app/', year: 2026 },
  { title: 'Castivo', description: 'Creator software for branded streamer sites and audience engagement tools.', image: '/images/projects/screenshots/castivo.png', tags: ['Next.js', 'Firebase', 'Creator Tools'], href: 'https://castivo-web-thejhyefactors-projects.vercel.app/', year: 2026 },
  { title: 'QuickMeet', description: 'A focused meeting platform for starting secure conversations quickly.', image: '/images/projects/screenshots/quickmeet.png', tags: ['React', 'WebRTC', 'Real-time'], href: 'https://www.quickmeet.cam/', year: 2026 },
]

export default function Home() {
  return <div className="page-shell">
    <section className="grid min-h-[620px] items-center gap-12 py-24 md:grid-cols-[1.2fr_0.8fr] md:py-32">
      <div><p className="eyebrow mb-6">Full-stack developer · Tokyo / Australia</p><h1 className="text-balance max-w-3xl font-['Space_Grotesk'] text-5xl font-bold leading-[0.98] tracking-[-0.04em] md:text-7xl">I build useful software for real work.</h1><p className="mt-8 max-w-xl text-lg leading-8 text-[var(--muted)]">I&apos;m Jhye O&apos;Meley, a 23-year-old developer building web applications, automation, and operational systems with clarity and care.</p><div className="mt-9 flex flex-wrap gap-5"><Link href="/portfolio/" className="focus-ring inline-flex items-center gap-2 bg-[var(--ink)] px-5 py-3 text-sm font-bold text-white hover:bg-[var(--accent)]">View selected work <ArrowUpRight className="h-4 w-4" /></Link><Link href="/contact/" className="focus-ring inline-flex items-center gap-2 border border-[var(--border)] px-5 py-3 text-sm font-bold hover:border-[var(--accent)] hover:text-[var(--accent)]">Get in touch</Link></div><div className="mt-10 flex gap-5 text-sm text-[var(--muted)]"><a className="focus-ring inline-flex items-center gap-2 hover:text-[var(--accent)]" href="https://github.com/TheJhyeFactor" target="_blank" rel="noreferrer"><Github className="h-4 w-4" />GitHub</a><a className="focus-ring inline-flex items-center gap-2 hover:text-[var(--accent)]" href="https://www.linkedin.com/in/jhye-o-meley-529960213/" target="_blank" rel="noreferrer"><Linkedin className="h-4 w-4" />LinkedIn</a><a className="focus-ring inline-flex items-center gap-2 hover:text-[var(--accent)]" href="mailto:omelejhye@gmail.com"><Mail className="h-4 w-4" />Email</a></div></div>
      <div className="border-l border-[var(--border)] pl-7 md:pl-10"><p className="eyebrow mb-5">At a glance</p><dl className="space-y-7"><div><dt className="text-4xl font-bold tracking-tight">22</dt><dd className="mt-1 text-sm text-[var(--muted)]">projects delivered</dd></div><div><dt className="text-4xl font-bold tracking-tight">5</dt><dd className="mt-1 text-sm text-[var(--muted)]">product platforms built</dd></div><div><dt className="text-4xl font-bold tracking-tight">5 yrs</dt><dd className="mt-1 text-sm text-[var(--muted)]">building since 2021</dd></div></dl></div>
    </section>
    <section className="section-rule py-16 md:py-20"><div className="mb-10 flex items-end justify-between gap-6"><div><p className="eyebrow mb-3">Selected work</p><h2 className="font-['Space_Grotesk'] text-3xl font-bold tracking-tight md:text-4xl">Products I&apos;ve built</h2></div><Link href="/portfolio/" className="focus-ring hidden text-sm font-bold text-[var(--accent)] hover:underline sm:block">View all work <ArrowUpRight className="inline h-4 w-4" /></Link></div><div className="grid gap-6 md:grid-cols-2">{products.slice(0, 4).map((project) => <ProjectCard key={project.title} {...project} featured />)}</div><Link href="/portfolio/" className="focus-ring mt-8 block text-sm font-bold text-[var(--accent)] hover:underline sm:hidden">View all work <ArrowUpRight className="inline h-4 w-4" /></Link></section>
    <section className="section-rule grid gap-8 py-16 md:grid-cols-[0.8fr_1.2fr] md:py-20"><div><p className="eyebrow mb-3">What I do</p><h2 className="font-['Space_Grotesk'] text-3xl font-bold tracking-tight">Clear systems for complicated work.</h2></div><div className="grid gap-x-8 gap-y-6 text-[var(--muted)] sm:grid-cols-2"><p><strong className="block text-[var(--ink)]">Full-stack development</strong>Web applications designed to be useful, maintainable, and ready for production.</p><p><strong className="block text-[var(--ink)]">Automation & integrations</strong>Connected workflows that remove repetitive work and keep teams moving.</p><p><strong className="block text-[var(--ink)]">Operational tools</strong>Dashboards and systems that turn live information into confident decisions.</p><p><strong className="block text-[var(--ink)]">AI/ML prototypes</strong>Practical experiments that test what new technology can do.</p></div></section>
  </div>
}
