import type { Metadata } from 'next'
import { ArrowUpRight, Github } from 'lucide-react'
import { openSourceProjects } from '@/data/portfolio'

export const metadata: Metadata = { title: 'Open source', description: 'Public tools, open experiments, and practical findings from Jhye O’Meley.', alternates: { canonical: '/open-source/' } }

export default function OpenSourcePage() {
  return <div className="page-shell"><section className="grid gap-10 py-20 md:grid-cols-[1.1fr_0.7fr] md:items-end md:py-28"><div><p className="eyebrow mb-5">Open source · Public work</p><h1 className="display-title">Tools I share. Findings I keep testing.</h1></div><p className="text-lg leading-8 text-[var(--muted)]">Small, useful projects are where I explore privacy, browser-native workflows, and the edges of product engineering in public.</p></section><section className="section-block" aria-labelledby="open-source-projects"><div className="section-heading"><div><p className="eyebrow mb-3">01 · Projects</p><h2 id="open-source-projects" className="section-title">Public experiments with a job to do.</h2></div><span className="mono-label">{openSourceProjects.length} projects</span></div><div className="work-list">{openSourceProjects.map((project, index) => <article key={project.title} className="open-source-entry"><span className="mono-label">0{index + 1}</span><div><p className="eyebrow mb-2">{project.type}</p><h3 className="font-display text-3xl font-bold tracking-[-0.035em]">{project.title}</h3><p className="mt-3 leading-7 text-[var(--muted)]">{project.description}</p><p className="mt-4 text-sm leading-6">{project.note}</p><div className="mt-6 flex flex-wrap gap-5"><a className="text-link" href={project.href} target="_blank" rel="noreferrer">Open project <ArrowUpRight className="h-4 w-4" /></a><a className="text-link" href={project.repo} target="_blank" rel="noreferrer"><Github className="h-4 w-4" /> View repository</a></div></div></article>)}</div></section><section className="statement-block"><p className="eyebrow">What I publish</p><div><h2 className="section-title max-w-3xl">Notes on building software that stays understandable.</h2><p className="mt-5 max-w-2xl leading-7 text-[var(--muted)]">The journal is where I turn project work into reusable observations.</p></div></section></div>
}
